# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d18905e180abbe1a5035cc7195f0919800dc3abdcca92bd0be2052bf7e35c495071ee5ee94b524565097bce8ec09fe85c7758d8ca95513d831c801dcd0e2e1a3

test:
  secret_key_base: 90d4a28cd86a99a809f6318270d6302ccd1987a5167b49166f04043ad654def1baae9ecb91dfab93ce02792d43ae7b90bb5afc3c1dee66d23a9160a9f2960563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
